networks:
  fleet-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  grafana_data:
  mosquitto_data:
  mosquitto_log:
  
services:  
  postgres: 
    image: postgres:16-alpine
    container_name: fleet-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: keycloak_db          
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fleet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d keycloak_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: fleet-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - fleet-network
  # ════════════════════════════════
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    container_name: fleet-keycloak
    restart: unless-stopped
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fleet-network
    healthcheck:
      test: ["CMD", "bash", "-lc", "echo > /dev/tcp/127.0.0.1/9000"]
      interval: 10s
      timeout: 5s
      retries: 5  
      start_period: 30s  
  
  # ════════════════════════════════

  # collector-service:
  #   build:
  #     context: ./collector
  #     dockerfile: Dockerfile
  #   container_name: fleet-collector-service
  #   restart: unless-stopped
  #   ports:
  #     - "8881:8881"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     KEYCLOAK_REALM: ${KEYCLOAK_REALM}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     keycloak:
  #       condition: service_healthy
  #   networks:
  #     - fleet-network
    # ════════════════════════════════
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: fleet-api-gateway
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      SPRING_PROFILES_ACTIVE: docker
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ANGULAR_APP_URL: ${ANGULAR_APP_URL}
    depends_on:
      keycloak:
        condition: service_healthy
      redis:
        condition: service_started
      # collector-service:
      #   condition: service_started
    networks:   
      - fleet-network
    # ════════════════════════════════ 
  redis : 
    image: redis:7-alpine
    container_name: fleet_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - fleet-network
  
  # ════════════════════════════════ 
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fleet-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    environment:
      API_GATEWAY_URL: ${API_GATEWAY_URL:-http://api-gateway:8888}
    depends_on:
      - api-gateway
    networks:
      - fleet-network 
# # ════════════════════════════════
  # grafana:
  #   image: grafana/grafana:11.3.0
  #   container_name: fleet-grafana
  #   restart: unless-stopped
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
  #     GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #     - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  #   networks:
  #     - fleet-network
  # ════════════════════════════════
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: fleet-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - fleet-network

  mqtt-device-simulator:
    build:
      context: ./mqtt-device-simulator
      dockerfile: Dockerfile
    container_name: fleet-mqtt-device-simulator
    restart: unless-stopped
    environment:
      SIMULATOR_BROKER_URL: tcp://mosquitto:1883
      SIMULATOR_TRAIN_ID: ${SIMULATOR_TRAIN_ID:-TRAIN-001}
      SIMULATOR_INTERVAL_MS: ${SIMULATOR_INTERVAL_MS:-3000}
    depends_on:
      mosquitto:
        condition: service_started
    networks:
      - fleet-network
